#!/usr/bin/env python3
"""Static source audit; requires beautifulsoup4. Not an AI detector or medical review."""
from pathlib import Path
from bs4 import BeautifulSoup
from urllib.parse import urlsplit, unquote
import collections, json, re, unicodedata, xml.etree.ElementTree as ET
ROOT = Path(__file__).resolve().parents[1]
files = sorted(ROOT.glob('*.html'))
pages = {('/' if f.stem == 'index' else '/' + f.stem): BeautifulSoup(f.read_text(), 'html.parser') for f in files}
redirects = dict(re.findall(r'location = (\S+) \{ return 301 ([^$;]+)', (ROOT/'nginx.conf.template').read_text()))
errors, rows, canonicals = [], [], []
markers = re.compile(r'watermark|generated by|synthid|c2pa|contentReference|oaicite|as an ai|data-start|data-end', re.I)
for f, (route, soup) in zip(files, pages.items()):
    raw = f.read_text()
    issues = []
    for tag in ['h1','main','title']:
        if len((soup.head if tag == 'title' else soup).find_all(tag)) != 1: issues.append(f'{tag}: expected one')
    desc = soup.find('meta', attrs={'name':'description'})
    if not desc or not desc.get('content'): issues.append('missing description')
    c = soup.find('link', rel='canonical')
    expected = 'https://getgummygains.com' + route
    if not c or c.get('href') != expected: issues.append('wrong canonical')
    canonicals.append(c.get('href') if c else '')
    ids = [x['id'] for x in soup.select('[id]')]
    if len(ids) != len(set(ids)): issues.append('duplicate IDs')
    for script in soup.find_all('script', type='application/ld+json'):
        try: json.loads(script.string or script.get_text())
        except Exception: issues.append('invalid JSON-LD')
    for tag, attr in [('a','href'),('script','src'),('link','href'),('img','src')]:
        for a in soup.find_all(tag):
            href = a.get(attr, '')
            if not href or href.startswith(('data:','mailto:','tel:','javascript:')): continue
            u = urlsplit(href)
            if u.netloc and u.netloc != 'getgummygains.com': continue
            path = unquote(u.path) or route
            if not path.startswith('/'): path = '/' + path
            path = redirects.get(path, path)
            target = pages.get(path)
            if target is None and path.endswith('.html'): target = pages.get(path[:-5])
            if target is None:
                if not (ROOT/path.lstrip('/')).exists(): issues.append(f'broken {attr}: {href}')
            elif u.fragment and not target.find(id=unquote(u.fragment)):
                issues.append(f'missing fragment: {href}')
    invisible = sorted(set(f'U+{ord(ch):04X}' for ch in raw if unicodedata.category(ch)=='Cf'))
    hits = sorted(set(m.group(0) for m in markers.finditer(raw)))
    rows.append({'file': f.name, 'route':route, 'title':soup.title.get_text() if soup.title else '',
                 'main_words':len(soup.main.get_text(' ',strip=True).split()) if soup.main else 0,
                 'format_characters':invisible, 'provenance_marker_matches':hits, 'issues':issues})
    errors += [f'{f.name}: {v}' for v in issues]
if len(canonicals) != len(set(canonicals)): errors.append('duplicate canonical URLs')
ns={'s':'http://www.sitemaps.org/schemas/sitemap/0.9'}
sitemap=[e.text for e in ET.parse(ROOT/'sitemap.xml').findall('s:url/s:loc',ns)]
if set(sitemap)!=set(canonicals): errors.append('sitemap/canonical mismatch: '+str(set(sitemap)^set(canonicals)))
image_markers = {}
for f in (ROOT/'assets/product').glob('*'):
    if f.is_file():
        hits=[x.decode() for x in [b'C2PA',b'c2pa',b'SynthID',b'OpenAI',b'DALL',b'CreatorTool'] if x in f.read_bytes()]
        image_markers[str(f.relative_to(ROOT))]=hits
report={'checked':'2026-09-24','scope':'Static HTML, internal links/fragments/assets, canonical/sitemap, JSON syntax, named literal and Unicode-format marker scan. No classifier; no exhaustive image provenance, medical-claim, ranking or penalty verification.', 'pages':len(rows), 'sitemap_urls':len(sitemap), 'errors':errors, 'image_literal_scan':image_markers, 'rows':rows}
(ROOT/'docs/site-audit-2026-09-24.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'pages':len(rows),'sitemap_urls':len(sitemap),'errors':errors,'format_character_pages':sum(bool(x['format_characters']) for x in rows),'marker_match_pages':sum(bool(x['provenance_marker_matches']) for x in rows),'product_images':len(image_markers)},indent=2))
raise SystemExit(bool(errors))
